---
title: "Results"
format:
    html:
        theme: cosmo
        toc: true
execute:
    echo: true
    warning: false
    error: false
---

::: {.panel-tabset}

## Overall sample

### Inclusion flow diagram

```{r}
library(targets)
library(survival)
library(data.table)

flow <- as.data.table(tar_read(selection_process))
flow[, `:=`(
    Total_cohort = total_cohort,
    Agreed_accel_study = accel_available,
    Valid_accel_data = GGIR_checks,
    No_prev_dementia = no_prevalent_dementia,
    Aged_55_over = age_55_over
)]

flow[, list(
    Total_cohort,
    Agreed_accel_study,
    Valid_accel_data,
    No_prev_dementia,
    Aged_55_over
)]

```

### Testing proportional hazards

#### SRI

```{r}
plot(tar_read(schoenfeld_sri_model1), var = 1)
```

#### RRI

```{r}
library(targets)
plot(tar_read(schoenfeld_rri_model1), var = 1)
```

#### IS

```{r}
library(targets)
plot(tar_read(schoenfeld_IS_model1), var = 1)
```

### P values for interaction/linearity null hypotheses

```{r}
tar_read(assumption_checks_all)
```

### Hazard ratio estimate

```{r}
tar_read(pooled_estimates_all)
```

## Males aged 65-75 years
### P values for interaction/linearity null hypotheses

```{r}
tar_read(assumption_checks_65_to_75_males)
```

### Hazard ratio estimate

```{r}
tar_read(pooled_estimates_65_to_75_males)
```

## Females aged 65-75 years
### P values for interaction/linearity null hypotheses

```{r}
tar_read(assumption_checks_65_to_75_females)
```

### Hazard ratio estimate

```{r}
tar_read(pooled_estimates_65_to_75_females)
```

:::